version: "3.7"

services:
  camera:
    image: camera
    container_name: camera

    build:
      context: .

    env_file:
      - .env

    restart: always

    labels:
      - "traefik.enable=true"

      # Только camera.boxhoster.com
      - "traefik.http.routers.camera.rule=Host(`camera.boxhoster.com`)"
      - "traefik.http.routers.camera.entrypoints=websecure"
      - "traefik.http.routers.camera.tls.certresolver=production"

      # Внутренний порт контейнера
      - "traefik.http.services.camera.loadbalancer.server.port=80"

    networks:
      - traefik

networks:
  traefik:
    external: true
