version: "3.7"

services:
  camera:
    env_file:
      - .env

    build:
      context: .
    image: camera
    container_name: camera

    # Persist data across redeploys
    volumes:
      - "camera_storage:/rails/storage"
      - "camera_hls:/rails/public/hls"

    restart: always

    labels:
      - "traefik.enable=true"

      # Only camera.boxhoster.com
      - "traefik.http.routers.camera.rule=Host(`camera.boxhoster.com`)"
      - "traefik.http.routers.camera.entrypoints=websecure"
      - "traefik.http.routers.camera.tls.certresolver=production"

      # Internal container port
      - "traefik.http.services.camera.loadbalancer.server.port=80"

    networks:
      - traefik

volumes:
  camera_storage:
  camera_hls:

networks:
  traefik:
    external: true
